Traceback (most recent call last):
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\site-packages\nbclient\client.py", line 778, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\site-packages\jupyter_core\utils\__init__.py", line 198, in ensure_async
    result = await obj
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\site-packages\jupyter_client\channels.py", line 313, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\site-packages\nbclient\client.py", line 1001, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\site-packages\nbclient\client.py", line 802, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "C:\Users\jesus\miniconda3\envs\testml_env\lib\site-packages\nbclient\client.py", line 852, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['# === Predicted values for the training set using the KNN model ===', 'y_train_pred_knn = knn_model.predict(X_train)', '', '# === Plotting actual vs predicted values for the training set ===', 'plt.figure(figsize=(8, 6))']
...
["plt.xlabel('Actual Values (y_train)')", "plt.ylabel('Predicted Values (y_train_pred)')", 'plt.legend()', 'plt.grid(alpha=0.3)', 'plt.show()']
-------------------

